# Generated by Django 2.2.10 on 2020-03-03 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.PositiveSmallIntegerField(default=170),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=70),
            preserve_default=False,
        ),
    ]
