# Generated by Django 2.2.10 on 2020-03-03 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20200228_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='log',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='log',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
