# Generated by Django 2.2.10 on 2020-03-03 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20200303_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='logs.Food'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
